<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-28T22:15:11 IST" name="Suite" finished-at="2023-12-28T22:16:13 IST" duration-ms="61973">
    <groups>
    </groups>
    <test started-at="2023-12-28T22:15:11 IST" name="SubmitOrderTest" finished-at="2023-12-28T22:15:51 IST" duration-ms="39796">
      <class name="rahulshettyacademy.testcomponents.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:11 IST" name="launchApplication" finished-at="2023-12-28T22:15:16 IST" duration-ms="5448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:16 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-28T22:15:28 IST" duration-ms="11837" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=princessV*1, product=ADIDAS ORIGINAL, email=applevr@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:28 IST" name="launchApplication" finished-at="2023-12-28T22:15:32 IST" duration-ms="3968" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:32 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-28T22:15:45 IST" duration-ms="12328" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=princessV*1, product=IPHONE 13 PRO, email=applevr@outlook.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:45 IST" name="launchApplication" finished-at="2023-12-28T22:15:49 IST" duration-ms="4684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistory()[pri:0, instance:rahulshettyacademy.testcomponents.StandAloneTest@15713d56]" started-at="2023-12-28T22:15:49 IST" name="OrderHistory" finished-at="2023-12-28T22:15:51 IST" depends-on-methods="rahulshettyacademy.testcomponents.StandAloneTest.submitOrder" duration-ms="1280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
      </class> <!-- rahulshettyacademy.testcomponents.StandAloneTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2023-12-28T22:15:51 IST" name="ErrorValidationTests" finished-at="2023-12-28T22:16:13 IST" duration-ms="21527">
      <class name="rahulshettyacademy.testcomponents.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.testcomponents.ErrorValidations@539d019]" started-at="2023-12-28T22:15:51 IST" name="launchApplication" finished-at="2023-12-28T22:15:56 IST" duration-ms="4515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:rahulshettyacademy.testcomponents.ErrorValidations@539d019]" started-at="2023-12-28T22:15:56 IST" name="loginErrorValidation" finished-at="2023-12-28T22:15:57 IST" duration-ms="836" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rahulshettyacademy.testcomponents.ErrorValidations.loginErrorValidation(ErrorValidations.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.testcomponents.ErrorValidations@539d019]" started-at="2023-12-28T22:15:57 IST" name="launchApplication" finished-at="2023-12-28T22:16:01 IST" duration-ms="4063" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:rahulshettyacademy.testcomponents.ErrorValidations@539d019]" started-at="2023-12-28T22:16:01 IST" name="productErrorValidation" finished-at="2023-12-28T22:16:13 IST" duration-ms="11585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
      </class> <!-- rahulshettyacademy.testcomponents.ErrorValidations -->
    </test> <!-- ErrorValidationTests -->
  </suite> <!-- Suite -->
</testng-results>
